version: '3.8'

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "4000:4000"
    # env_file:
    #   - ./Backend/.env
    environment:
      - PORT=4000
      - MONGODB_URI=mongodb://mongo:27017/rbac  # Replace 'mydatabase' with your actual database name
    depends_on:
      - mongo
    volumes:
      - ./Backend:/src  # Optional: mount for development

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  frontend:
    environment:
    - VITE_BASE_URL=http://backend:4000
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    # env_file:
    #   - ./Frontend/.env
    

volumes:
  mongo-data:
